version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: simonravitz
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
<<<<<<< HEAD
      DATABASE_URL: 'postgresql+psycopg2://simonravitz:Aa123456!@host.docker.internal:5432/crmdb'
=======
      DATABASE_URL: postgresql+psycopg2://simonravitz:your_password@db:5432/your_database
>>>>>>> f0ae657d6e8455067a87cef92b8ffd1a79880ab7
    depends_on:
      - db
