apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-app.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "fastapi-app.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ include "fastapi-app.name" . }}
