apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-app.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "fastapi-app.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fastapi-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fastapi-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: "simonravitz"
        - name: POSTGRES_PASSWORD
          value: "Aa123456!"
        - name: POSTGRES_DB
          value: "crmdb"
        ports:
        - containerPort: 5432
