# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'fastapi-app'
        static_configs:
          - targets: ['fastapi-app-new-employee-app:80']
      - job_name: 'postgres'
        static_configs:
          - targets: ['fastapi-app-new-employee-app-postgres:5432']
