global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi-app-new-employee-app:80']  # Replace with your FastAPI service name and port

  - job_name: 'postgres'
    static_configs:
      - targets: ['fastapi-app-new-employee-app-postgres:5432']  # Replace with your PostgreSQL service name and port
