"""Add product_version table

Revision ID: 02a697d870c4
Revises: ebc21451eb99
Create Date: 2024-08-31 11:12:44.411592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a697d870c4'
down_revision: Union[str, None] = 'ebc21451eb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_version',
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('environment')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('product_version')
    # ### end Alembic commands ###
