"""Add build_time column to ProductVersion table

Revision ID: 18d4f8a8fa5f
Revises: 02a697d870c4
Create Date: 2024-08-31 11:43:21.793174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d4f8a8fa5f'
down_revision: Union[str, None] = '02a697d870c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_version', sa.Column('build_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_version', 'build_time')
    # ### end Alembic commands ###
