"""Add employees table

Revision ID: 1eb5304ac74b
Revises: c1e77380323a
Create Date: 2024-08-02 14:38:57.731210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb5304ac74b'
down_revision: Union[str, None] = 'c1e77380323a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employees',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('emp_id', sa.String, index=True),
        sa.Column('name', sa.String, index=True),
        sa.Column('position', sa.String, index=True),
        sa.Column('salary', sa.Numeric),
        sa.Column('creation_time', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('last_update_time', sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
