"""Add managers entity

Revision ID: 2908060f8be4
Revises: 4d5772b26a37
Create Date: 2024-09-16 18:05:17.021355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2908060f8be4'
down_revision: Union[str, None] = '4d5772b26a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('man_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('salary', sa.Numeric(), nullable=True),
    sa.Column('creation_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_domain'), 'managers', ['domain'], unique=False)
    op.create_index(op.f('ix_managers_id'), 'managers', ['id'], unique=False)
    op.create_index(op.f('ix_managers_man_id'), 'managers', ['man_id'], unique=False)
    op.create_index(op.f('ix_managers_name'), 'managers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_name'), table_name='managers')
    op.drop_index(op.f('ix_managers_man_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_domain'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
