"""Detect model changes

Revision ID: 4d5772b26a37
Revises: 5b1885d9dc8a
Create Date: 2024-09-11 18:48:57.759526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5772b26a37'
down_revision: Union[str, None] = '5b1885d9dc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('build_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('environment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
