"""Add test2 table

Revision ID: 739ad7a95a71
Revises: 52cd13bdbff4
Create Date: 2025-01-02 17:58:27.929770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739ad7a95a71'
down_revision: Union[str, None] = '52cd13bdbff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test2',
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('build_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('environment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test2')
    # ### end Alembic commands ###
