"""Add test4 table

Revision ID: adee6933f57c
Revises: 6ac6a57a47f1
Create Date: 2025-01-03 10:08:52.258814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adee6933f57c'
down_revision: Union[str, None] = '6ac6a57a47f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test4',
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('build_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('environment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test4')
    # ### end Alembic commands ###
