"""Add creation_time, last_update_time, and id columns

Revision ID: c1e77380323a
Revises: 
Create Date: 2024-08-02 14:36:02.674949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e77380323a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_emp_id', table_name='employees')
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_index('ix_employees_position', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('emp_id', name='employees_pkey')
    )
    op.create_index('ix_employees_position', 'employees', ['position'], unique=False)
    op.create_index('ix_employees_name', 'employees', ['name'], unique=False)
    op.create_index('ix_employees_emp_id', 'employees', ['emp_id'], unique=False)
    # ### end Alembic commands ###
