"""Add testdevsecops table

Revision ID: f467ac9602cd
Revises: 61ca9eef7f7e
Create Date: 2024-09-16 21:22:36.691302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f467ac9602cd'
down_revision: Union[str, None] = '61ca9eef7f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devsecops',
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('build_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('environment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devsecops')
    # ### end Alembic commands ###
