apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-system
  labels:
    app: employee-management-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-management-system
  template:
    metadata:
      labels:
        app: employee-management-system
    spec:
      serviceAccountName: employee-management-system-service-account
      containers:
        - name: employee-management-system
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL

              valueFrom:
                secretKeyRef:
                  name: employee-management-system-secret
                  key: database_url
