apiVersion: v1
kind: Service
metadata:
  name: employee-management-system-postgresql
spec:
  type: ClusterIP
  selector:
    app: employee-management-system-postgresql
  ports:
    - port: 5432
      targetPort: 5432
