apiVersion: v1
kind: Service
metadata:
  name: employee-management-system
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: employee-management-system
