# Service configuration
service:
  type: NodePort
  port: 8000
  nodePort: 32000  # Optional: specify a fixed NodePort, or let Kubernetes choose automatically

# Image configuration
image:
  repository: simon0101/employee-management-system-web
  tag: latest
  pullPolicy: IfNotPresent

# Environment variables (using Kubernetes secrets)
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: employee-management-system-secret
        key: database_url

# PostgreSQL configuration
postgresql:
  enabled: true
  postgresqlDatabase: crmdb
  postgresqlUsername: simonravitz
  postgresqlPassword:
    secretKeyRef:
      name: employee-management-system-secret
      key: postgresql_password
  service:
    port: 5432
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard
    accessModes:
      - ReadWriteOnce

# Ingress configuration (if needed)
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: employee-system.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Replicas configuration
replicaCount: 3

# Autoscaling configuration (if needed)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
