# Image settings
image:
  repository: simon658/fastapi-app
  tag: latest
  pullPolicy: Always  # Always pull the latest image

# Service settings
service:
  type: NodePort
  port: 80
  nodePort: 32000  # Exposing the service on this node port

# Ingress settings
ingress:
  enabled: false

# Namespace configuration
namespace: new-employee-app

# Defining resources with limits and requests
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Service account configuration
serviceAccount:
  create: true
  name: new-employee-app-service-account

# Autoscaling settings
autoscaling:
  enabled: true
  minReplicas: 3  # Setting a minimum of 3 replicas
  maxReplicas: 10  # Maximum replicas
  targetCPUUtilizationPercentage: 80  # Scale based on 80% CPU usage

# Environment variables using secrets for sensitive data
env:
  DATABASE_URL: "postgresql://$(DB_USER):$(DB_PASS)@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"

extraEnv:
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: username
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: password

# PostgreSQL configuration (managed via secrets)
postgres:
  host: fastapi-app-new-employee-app-postgres
  port: 5432
  database: crmdb
